services:
  web:
    container_name: nginx-container
    image: wed-nginx
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - client
      - server
    networks:
      - mynet

  client:
    container_name: client-container
    build:
      context: ./client-pre-pro
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - server
    networks:
      - mynet

  server:
    container_name: server-container
    build:
      context: ./server-pre-pro
      dockerfile: Dockerfile
    restart: always
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
